name: Cron Jobs
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Cron Job
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: List directory contents
          run: ssh -p 22 -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }} "ls -la"
