name: Cron Jobs
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Cron Job
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.SSH_PUBLIC_KEY }}
        if_key_exists: fail # replace / ignore / fail; optional ,(defaults to fail)
    - name: Run SSH command
      run: |
        ssh ${{secrets.SSH_USERNAME}}@${{secrets.SSH_IP}} "ls -la"
